Spotinstances
awslabs/aws-simple-ec2-cli pull request #64
Opened 2022-04-07 19:45 UTC by icarthick

Issue #, if available:
https://github.com/awslabs/aws-simple-ec2-cli/issues/55

Description of changes:
This PR includes the ability to request for Spot Instances. To accomplish this, I have introduced a new command line arg called "Ec2 Purchase Instance Type". This is an enum which supports one of these two choices "OnDemand" and "SpotInstance". If "SpotInstance" is chosen as the EC2 Purchase instance type, only then it would prompt the user for Spot Price. Depending on the spot price provided by the user, the Spot Instance Requests may or may not succeed. By default OnDemand instances will be chosen unless otherwise specified.

We are running out of flags, I have chosen "z" as the short flag name to specify Ec2 Purchase Instance Type and "x" as the short flag name for specifying Spot Instance Price. Am happy to change them if needed

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-11 20:40 UTC, snay2 requested changes
Thanks for the PR! This is a good start.

I'm not sold yet on whether this is the right "simple-ec2"-flavored customer experience for launching Spot--we ask the user for a Spot bid price separately from the instance type, without guidance on what those choices should be, and we're not much help if that Spot request fails (should they choose a different instance type? Increase their bid? Use a different region/AZ? Give up and use On Demand?). I wonder if we can provide more guidance or do some additional heavy lifting for the user, so that even someone who's never used Spot before can run it successfully with the defaults.

Spot is a potentially complex product, so I want to make sure we can provide a simple enough experience while still allowing the necessary flexibility.

2022-04-11 20:46 UTC, icarthick commented on cmd/launch.go
> +	creds := processcreds.NewCredentials("isengardcli credentials --awscli --role Admin carthick+webeip1@amazon.com")
Good catch, pushed the change

2022-04-18 15:06 UTC, icarthick commented on README.md
> +  -x, --spot-price float                 The price at which spot instances
Addressed

2022-04-18 15:06 UTC, icarthick commented on pkg/cli/cli.go
> +	Ec2PurchanceInstanceType         = "Ec2 Purchase Instance Type"
Addressed

2022-04-18 15:06 UTC, icarthick commented on pkg/config/config.go
> +	Ec2PurchaseInstanceType       Ec2PurchseInstanceType
Addressed

2022-04-18 15:06 UTC, icarthick commented on pkg/ec2helper/ec2helper.go
> +	//input.SecurityGroupIds = aws.StringSlice(selectedSecurityGroupIds)
Addressed

2022-04-18 15:07 UTC, icarthick commented on cmd/launch.go
> +		`The purchase type of the instance. Allowed values "On Demand" and "Spot Instance"`)
Addressed

2022-04-18 15:07 UTC, icarthick commented on cmd/launch.go
> +	if simpleConfig.Ec2PurchaseInstanceType == "" {
Addressed

2022-04-18 15:07 UTC, icarthick commented on pkg/ec2helper/ec2helper.go
> +	if simpleConfig.BootScriptFilePath != "" {
Addressed

2022-04-18 15:21 UTC, icarthick commented on pkg/config/config.go
> +		flagConfig.AutoTerminationTimerMinutes = 0
Addressed

2022-04-18 15:21 UTC, icarthick commented on pkg/config/config.go
> +func ToPurchaseInstanceType(enumString string) Ec2PurchseInstanceType{
Addressed

2022-04-18 15:22 UTC, icarthick commented on pkg/ec2helper/ec2helper.go
> +	//input.SubnetId = selectedSubnetId
Addressed

2022-04-18 21:30 UTC, brycahta commented
@icarthick -- Appreciate the PR and helping us build out this feature, but I share @snay2 's concerns with respect to Spot's complexity. Instead of a PR to start, the next steps for implementing Spot would be a design document/proposal outlining various details such as: which underlying api to use and why, what level of abstraction should we implement (i.e. I want to request the cheapest spot), should spot be its own subcommand etc. 

Our team plans to submit a PR containing the design proposal for the community to review in the near future, and I will update the original issue communicating the same. With that said, I'm closing this PR for now and if you have any other ideas/comments feel free to comment on the issue or upcoming design.

2022-04-18 21:30 UTC, closed without merging